export default [
    "highcharts.js",
    "highcharts.src.js",
    "highcharts-more.js",
    "highcharts-more.src.js",
    "highcharts-3d.js",
    "highcharts-3d.src.js",
    "modules/accessibility.js",
    "modules/accessibility.src.js",
    "modules/annotations.js",
    "modules/annotations.src.js",
    "modules/boost.js",
    "modules/boost.src.js",
    "modules/broken-axis.js",
    "modules/broken-axis.src.js",
    // "modules/canvas-tools.js",
    // "modules/canvas-tools.src.js",
    "modules/data.js",
    "modules/data.src.js",
    "modules/exporting.js",
    "modules/exporting.src.js",
    "modules/drilldown.js",
    "modules/drilldown.src.js",
    "modules/funnel.js",
    "modules/funnel.src.js",
    "modules/heatmap.js",
    "modules/heatmap.src.js",
    "modules/no-data-to-display.js",
    "modules/no-data-to-display.src.js",
    "modules/offline-exporting.js",
    "modules/offline-exporting.src.js",
    "modules/solid-gauge.js",
    "modules/solid-gauge.src.js",
    "modules/treemap.js",
    "modules/treemap.src.js"
]
