name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Setup config.json
        run: echo '{"token":"","port":"90","repo":"highcharts/highcharts"}' > config.json

      - name: Run tests
        run: npm test
